### ISSUE TITLE
XDC Community - Meeting 1 - XIPs

### ISSUE THREAD

**Issue by Tpada13** [XDC-Community/pm#1]
### Location
XDC Community Discord: https://discord.gg/H34D7h6Y
XDC Community voice channel

### Day & Time
Wednesday August 31, 2022 10am EDT (UTC -4)

Call will be recorded and archived for future XIP reference

### Agenda
- XIP-1 discussion & adoption 
- Governance & consensus methods
- Becoming an editor
- Time zones for future meetings

**Comment by WalterBlueu** [comment]
- [August 31, 2022, 14:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/aug-31-2022/2pm)
- Duration: 38 minutes
- Audio Recording: https://storx.io/16d7a33a0c
- Presentation: https://storx.io/f4de2d30e1
- https://github.com/XDC-Community/XIPs.github.io/pull/3#issue-1358828287
